import os

replacements = {
    "打开工程": "Open Project",
    "保存工程": "Save Project",
    "打开工程文件": "Open Project File",
    "保存工程文件": "Save Project File",
    "📂 训练集 (Train) [0个样本]": "📂 Train Set [0 samples]",
    "📂 验证集 (Val) [0个样本]": "📂 Val Set [0 samples]",
    "📂 测试集 (Test) [0个样本]": "📂 Test Set [0 samples]",
    "个样本]": " samples]",
    "未知 [": "Unknown [",
    "📂 训练集 (Train) [过滤: ": "📂 Train Set [Filtered: ",
    "📂 验证集 (Val) [过滤: ": "📂 Val Set [Filtered: ",
    "📂 测试集 (Test) [过滤: ": "📂 Test Set [Filtered: ",
    "打开工程失败": "Open Project Failed",
    "保存工程失败": "Save Project Failed",
    "无法打开工程文件:\\n": "Cannot open project file:\\n",
    "无法保存工程文件:\\n": "Cannot save project file:\\n",
    "选择VOC格式数据集根目录": "Select VOC Dataset Root Dir",
    "请先通过「添加样本」加载 VOC 数据集。": "Please load VOC dataset via 'Add Sample'.",
    "当前没有加载任何数据集，请先加载数据。": "No dataset loaded, please load data first.",
    " 加载VOC数据集": " Load VOC Dataset",
    " | 无标签": " | No Label",
    " | 已加载标签": " | Loaded Label",
    " | 样本数: ": " | Samples: ",
    " 数据集)": " Dataset)",
    "未加载数据集": "Dataset Not Loaded",
    "✅ 已保存 ": "✅ Saved ",
    "没有可用的样本进行重新划分。": "No samples available for resplit.",
    "保存数据集划分到txt文件": "Save dataset split to txt file",
    "错误：未知的数据集类型 '": "Error: Unknown dataset type '",
    "未知的划分模式: ": "Unknown split mode: ",
    "数据集已重新划分:\\nTrain: ": "Dataset resplit:\\nTrain: ",
    "✅ 找到配置 (递归): ": "✅ Found config (recursive): ",
    "⚠️ 自动查找失败，请手动选择 base config 文件": "⚠️ Auto-find failed, please manually select base config",
    "❌ 未找到 ": "❌ Not found ",
    "❌ 加载 ": "❌ Load ",
    " 失败: ": " Failed: ",
    "✅ 类别权重已应用到任务配置": "✅ Class weights applied to task config",
    "✅ 已批量应用所有推荐参数": "✅ Applied all recommended params",
    "💡 推荐配置已应用": "💡 Recommended config applied",
    "请核查以下配置无误后再点击「开始训练」：": "Please verify the following config before starting training:",
    "类别数量:": "Classes:",
    "算法 / Backbone:": "Algorithm / Backbone:",
    "学习率 / 优化器:": "LR / Optimizer:",
    "验证间隔:": "Val Interval:",
    "影像后缀 / 掩膜后缀:": "Image / Mask Suffix:",
    "▶ 开始训练": "▶ Start Training",
    "📄 查看完整配置": "📄 View Full Config",
    "取消": "Cancel",
    "尚未生成训练配置文件。\\n请先点击「运行」生成配置。": "Training config not generated.\\nPlease click 'Run' to generate.",
    "🚀 训练已启动！": "🚀 Training started!",
    "🚀 训练进行中...": "🚀 Training in progress...",
    "✅ 训练顺利完成！": "✅ Training successfully completed!",
    "⏸ 用户取消了训练": "⏸ User cancelled training",
    "❌ 训练错误: ": "❌ Training error: ",
    "当前训练环境校验未通过：\\n\\n": "Current training env validation failed:\\n\\n",
    "环境未就绪": "Env Not Ready",
    "⚠️ 训练退出 (code: ": "⚠️ Training exit (code: ",
    "⚠️ 训练退出 (exit code: ": "⚠️ Training exit (exit code: ",
    "🚀 刚刚训练的模型 -> 发送至推理分析": "🚀 Model just trained -> Sent to Inference",
    "🚀 已自动流转至推理面板并触发模型加载": "🚀 Auto-routed to Inference panel and triggered load",
    "⚠️ 流转失败：未能在库中找到刚生成的模型记录": "⚠️ Route failed: Could not find generated model record",
    "✅ 推理完成，结果已就绪": "✅ Inference complete, results ready",
    "推理错误: ": "Inference error: ",
    "✅ 模型加载完成: ": "✅ Model load complete: ",
    "⚠️ [同步失败] 无法加载图像到GIS底图: ": "⚠️ [Sync Failed] Cannot load image to GIS base map: ",
    "🔄 [同步] GIS底图 -> 推理输入: ": "🔄 [Sync] GIS base map -> Inference input: ",
    "🔄 [同步] 推理输入 -> GIS底图: ": "🔄 [Sync] Inference input -> GIS base map: ",
    "已从 ": "From ",
    "📋 模型: ": "📋 Model: ",
    "📋 找到 ": "📋 Found ",
    "🔍 搜索 site-packages: ": "🔍 Searching site-packages: ",
    "✅ 配置已导出到: ": "✅ Config exported to: ",
    "错误": "Error",
    "提示": "Info",
    "当前工程: ": "Current Project: ",
    "批量添加样本": "Batch Add Samples",
    "正在分析样本... ": "Analyzing samples... ",
    "正在分析数据集...": "Analyzing dataset...",
    "正在计算数据集统计信息（后台进程）...": "Calculating dataset metadata (background)...",
    "✅ 使用缓存的元数据": "✅ Using cached metadata",
    "已加载元数据缓存": "Metadata cache loaded",
    "⚠️ 分析错误: ": "⚠️ Analysis error: ",
    "目录结构错误": "Directory Structure Error",
    "缺少 JPEGImages 目录（影像目录）": "Missing JPEGImages directory",
    "缺少 SegmentationClass 目录（标签目录）": "Missing SegmentationClass directory",
    "所选目录不是有效的VOC格式数据集。\\n\\n": "Selected directory is not a valid VOC dataset.\\n\\n",
    "不能删除顶级节点（Train/Val/Test）": "Cannot delete top-level nodes (Train/Val/Test)",
    "⚠️ 无法复制路径": "⚠️ Cannot copy path",
    "已复制路径: ": "Copied path: ",
    "🔗 复制完整路径": "🔗 Copy Full Path",
    "📋 复制文件名": "📋 Copy Filename",
    "🖼️  加载样本可视化: ": "🖼️ Load sample visualization: ",
    "⚠️ 未找到样本 ": "⚠️ Sample not found ",
    " 的影像文件。\\n\\n请确保数据目录结构正确：\\n- images/": "'s image file.\\n\\nEnsure correct structure:\\n- images/",
    " 的影像文件": "'s image file",
    "⚠️ 无法定位文件": "⚠️ Cannot locate file",
    "工程文件已加载/保存，但存在路径提示:\\n": "Project loaded/saved, but path issues:\\n",
    "工程路径提示": "Project Path Info",
    "任务配置模式": "Task Config Mode",
    "训练进行中": "Training in Progress",
    "网格视图: 无样本": "Grid View: No Samples",
    "切换到网格视图": "Switch to Grid View",
    "已切换到 ": "Switched to ",
    "已过滤显示 ": "Filtered display ",
    " 个样本": " samples",
    "   搜索模式: ": "   Search mode: ",
    "✅ 已加载 ": "✅ Loaded ",
    "❌ 推荐配置生成失败: ": "❌ Recommended config gen failed: ",
    "⚠️ 无可用的元数据数据库，请先加载数据集": "⚠️ No metadata DB, please load dataset",
    "已计算类别权重（Median Frequency Balancing）:\\n[": "Calculated class weights (Median Frequency Balancing):\\n[",
    "由于类别分布不均衡，推荐开启损失权重补偿": "Class imbalance detected, recommend loss weight compensation",
    "增加水平翻转以扩充数据及提高泛化": "Add HorizontalFlip for data augmentation",
    "光照扰动增加鲁棒性": "Add PhotometricDistortion for robustness",
    "旋转增强适应方向多变的地物": "Add RandomRotate for orientation variance",
    "基于数据集特点动态适配目标损失": "Dynamic loss adaptation based on dataset features",
    "]\\n\\n是否应用到任务配置？": "]\\n\\nApply to task config?",
    "类别权重": "Class Weight",
    "✅ 是": "✅ Yes",
    "否": "No",
    "自动": "Auto",
    "主窗口": "MainWindow",
    "📄 用户选择配置: ": "📄 User selected config: ",
    "📄 配置文件已生成: ": "📄 Config file generated: ",
    "📁 检测到标签目录: ": "📁 Detected label dir: ",
    "📂 工作目录: ": "📂 Work dir: ",
    ": 共 ": ": Total ",
    " | 优化器: ": " | Optimizer: ",
    "🔄 准备接收预测结果: ": "🔄 Prepare to receive prediction: ",
    "🎨 已应用可视化设置到主图": "🎨 Applied viz settings to main map",
    "⚠️ 清理 analysis_panel 线程时出错: ": "⚠️ Clean analysis_panel thread error: ",
    "⚠️ 清理 training 线程时出错: ": "⚠️ Clean training thread error: ",
    "⚠️ 清理 image_viewer 线程时出错: ": "⚠️ Clean image_viewer thread error: ",
    "⚠️ 清理 gisCanvas 线程时出错: ": "⚠️ Clean gisCanvas thread error: ",
    "📂 训练集 (Train) [": "📂 Train Set [",
    "📂 验证集 (Val) [": "📂 Val Set [",
    "📂 测试集 (Test) [": "📂 Test Set ["
}

file_path = 'd:/WorkSpace/RSegGUI/scripts/data_source_tree_example.py'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

for k, v in replacements.items():
    content = content.replace(k, v)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Main window replacement complete.")
