import os

directory = 'd:/WorkSpace/RSegGUI/ui/widgets'

replacements = {
    "底层字典覆写 (Dictionary Overrides)": "Dictionary Overrides",
    "在此处输入要强制覆盖的参数 (JSON 格式)：\\n例如：{\\\"model.decode_head.dropout_ratio\\\": 0.2}": "Enter parameters to forcefully override here (JSON format):\\nExample: {\\\"model.decode_head.dropout_ratio\\\": 0.2}",
    "JSON 格式错误: ": "JSON format error: ",
    "高级专家配置 (Expert Settings)": "Expert Settings",
    "🛠️ 开启高级专家配置 (Enable Expert Settings)": "🛠️ Enable Expert Settings",
    "🛠️ 高级专家配置 (Expert Settings)": "🛠️ Expert Settings",
    "清除所有的推荐标注": "Clear all recommendations",
    "一键应用本组件内的所有推荐项": "Apply all recommendations in this component",

    "</b> 项推荐，等待采纳：": "</b> recommendations waiting to be applied:",
    "</b> <span style='color: #666;'>(受影像波段影响)</span>": "</b> <span style='color: #666;'>(Affected by image bands)</span>",
    "· <b>裁剪大小</b>: 推荐 <b>": "· <b>Crop Size</b>: Recommend <b>",
    "✅ 一键全部应用": "✅ Apply All",
    "· <b>Loss 权重补偿</b>: 建议 <b>启用</b> <span style='color: #666;'>(针对类别不平衡现象)</span>": "· <b>Loss Weighting</b>: Recommend <b>Enable</b> <span style='color: #666;'>(For class imbalance)</span>",
    "</b> <span style='color: #666;'>(基于最小影像宽度 × 0.8)</span>": "</b> <span style='color: #666;'>(Based on min image width × 0.8)</span>",
    "⏳ 正在结合分析结果生成推荐配置...": "⏳ Generating recommended config based on analysis...",
    "💡 基于数据集特征，已生成 <b>": "💡 Based on dataset features, generated <b>",
    "✨ 获取数据驱动推荐": "✨ Get Data-Driven Recommendations",
    "· <b>输入通道数</b>: 推荐 <b>": "· <b>In Channels</b>: Recommend <b>",
    "⚠ 推荐值将分发到上下方各栏的相应位置（带有 💡 标记）\\n您也可以不去点击下方按钮，逐项在有指标的小图标上点击以分步采纳。": "⚠ Recommendations will be distributed to respective fields (marked with 💡)\\nYou can also click the lightbulb icons individually to apply.",
    "· <b>损失函数</b>: 推荐 <b>": "· <b>Loss Function</b>: Recommend <b>",

    "删除类别": "Delete Class",
    "检测到已有手动编辑的类别配置，是否用推荐结果覆盖？": "Manually edited class config detected. Override with recommendations?",
    "覆盖类别配置": "Override Class Config",
    "至少保留 2 个类别。": "Keep at least 2 classes.",
    "- 删除选中": "- Delete Selected",
    "颜色": "Color",
    "+ 添加类别": "+ Add Class",
    " 的颜色": "'s Color",
    "类别名称": "Class Name",

    "暂无数据": "No Data",
    "Px=像素统计 | Img=图像数 | Log=对数坐标 | NoBG=隐藏背景": "Px=Pixels | Img=Images | Log=Log Scale | NoBG=Hide BG",
    "📊 计算权重": "📊 Calculate Weights",

    " 张图像": " Images",
    "密集 (50%-90%)": "Dense (50%-90%)",
    "全覆盖 (>90%)": "Full (>90%)",
    "适中 (10%-50%)": "Moderate (10%-50%)",
    "稀疏 (<10%)": "Sparse (<10%)",

    "推荐值: ": "Recommended value: ",
    "\\n\\n🔹 点击应用此推荐": "\\n\\n🔹 Click to apply this recommendation",
    "已应用推荐值: ": "Applied recommended value: ",

    "\\n此 GUI 需要 MMSeg 1.x 配置格式，与 0.x 不兼容。\\n请运行: ": "\\nThis GUI requires MMSeg 1.x config format, incompatible with 0.x.\\nPlease run: ",
    "正在扫描 conda 环境，请稍候...": "Scanning conda environments, please wait...",
    "未选择 Python 环境，请在环境面板中选择或输入路径。": "No Python environment selected. Please select or input path in environment panel.",
    "请选择 Python 环境": "Please select Python environment",
    " 在训练时使用所选 Python 环境。\\n所需包：": " Use selected Python environment during training.\\nRequired packages: ",
    "❌ 版本不兼容: ": "❌ Version incompatible: ",
    "🔍 正在检测: ": "🔍 Detecting: ",
    "检测异常: ": "Detection exception: ",

    "极微小噪点 (<5px Area)": "Extremely Small Noise (<5px Area)",
    "图像或标签文件不存在": "Image or label file does not exist",
    "重新运行健康检查": "Rerun Health Check",
    "图像与标签尺寸不一致": "Image and label dimensions mismatch",
    "📋 复制路径": "📋 Copy Path",
    "清除过滤，显示所有样本": "Clear filter, show all samples",
    "导出失败": "Export Failed",
    "没有问题需要导出": "No issues to export",
    "提示": "Tip",
    "黑边/无数据区域超过 80%": "Black borders/nodata area exceeds 80%",
    "导出问题列表到 CSV 文件": "Export issue list to CSV file",
    "CSV 文件 (*.csv);;所有文件 (*.*)": "CSV Files (*.csv);;All Files (*.*)",
    "空标签样本 (Empty Masks)": "Empty Masks",
    " 条记录到:\\n": " records to:\\n",
    "已导出 ": "Exported ",
    "无法在文件管理器中显示文件:\\n": "Cannot show file in file manager:\\n",
    "标签中存在定义外的类别ID": "Undefined class ID exists in label",
    " 个文件路径到剪贴板": " file paths to clipboard",
    "使用 palette 设置标签颜色": "Use palette to set label colors",
    "文件损坏 (Corrupt Files)": "Corrupt Files",
    "尺寸不匹配 (Dimension Mismatch)": "Dimension Mismatch",
    "通道数异常 (Channel Mismatch)": "Channel Mismatch",
    "图像路径 (Image Path)": "Image Path",
    "自动修复可修复的警告": "Auto fix fixable warnings",
    "⚠️ 导出 CSV 失败: ": "⚠️ Export CSV failed: ",
    "标签路径 (Label Path)": "Label Path",
    "已复制": "Copied",
    " 项 ]": " items ]",
    "无效类别ID (Invalid Class ID)": "Invalid Class ID",
    " 个样本通过检查 )": " samples passed check )",
    "高无数据覆盖 (>80% Nodata)": "High Nodata Coverage (>80%)",
    " 类型的问题文件": " type issue files",
    "导出成功": "Export Success",
    "位深错误 (Dtype Mismatch)": "Dtype Mismatch",
    "导出所有问题到 CSV 文件": "Export all issues to CSV file",
    "标签全为背景类": "Label is all background",
    "文件缺失 (File Missing)": "File Missing",
    "📂 在文件管理器中显示": "📂 Show in File Manager",
    "问题描述 (Description)": "Description",
    "标签位深错误": "Label dtype error",
    "无法读取的图像或标签文件": "Unreadable image or label file",
    "图像或标签通道数异常": "Image or label channel mismatch",
    "📄 导出问题日志": "📄 Export Issue Log",
    "没有 ": "No ",
    "导出问题日志": "Export Issue Log",
    "样本ID (Sample ID)": "Sample ID",
    "问题类型 (Issue Type)": "Issue Type",
    "标签包含极小的噪声区域": "Label contains extremely small noise area",
    "详细信息 (Details)": "Details",

    "框架:": "Framework:",
    "算法:": "Algorithm:",
    "选择底层训练框架": "Select training framework",
    "选择模型的 Backbone 架构": "Select model's Backbone architecture",
    "选择分割算法/架构": "Select segmentation algorithm/architecture",

    "NIR假彩色 (4,3,2)": "NIR False Color (4,3,2)",
    "波段映射预设": "Band Mapping Presets",
    "数据源管理 (Data Source Manager)": "Data Source Manager",
    " (当前显示: R=": " (Current: R=",
    "📌 槽位已填充: ": "📌 Slot filled: ",
    "波段: ": "Bands: ",
    "请先切换到推理可视化模式，画布组件将自动加载。": "Please switch to inference visualization mode first, canvas will load automatically.",
    "选择右侧任务类型后\\n此处显示快速配置选项": "After selecting a task on the right,\\nquick config options will appear here.",
    "➕ 添加叠加层 (Add Overlay Raster)...": "➕ Add Overlay Raster...",
    "添加叠加图层": "Add Overlay Layer",
    "🖍️ 添加矢量 (Add Vector Layer)...": "🖍️ Add Vector Layer...",
    "图层控制 (Layer Control)": "Layer Control",
    "💡 点击 + 加载底图开始": "💡 Click + to load base image and start",
    "选择 VOC 格式数据集根目录（需包含 JPEGImages、SegmentationClass、ImageSets 目录）": "Select VOC format dataset root (must contain JPEGImages, SegmentationClass, ImageSets)",
    "图层 (Layers)": "Layers",
    "快速配置": "Quick Config",
    "卷帘对比 (Swipe Compare)": "Swipe Compare",
    "🗑️ 槽位已清空: ": "🗑️ Slot cleared: ",
    "添加图层": "Add Layer",
    " 通道对应的波段序号": " channel's band index",
    "📋 任务组已创建: ": "📋 Task group created: ",
    "波段: -": "Bands: -",
    "📂 加载数据集": "📂 Load Dataset",
    "📂 加载底图 (Set Base Image)...": "📂 Set Base Image...",

    "Zoom to Native Resolution - 缩放到原始分辨率 (1:1)": "Zoom to Native Resolution (1:1)",
    "Zoom to Last - 恢复上一次的缩放状态": "Zoom to Last",
    "🔲 适应窗口 (Zoom Full)": "🔲 Zoom Full",
    "Zoom Full - 适应窗口显示完整图像": "Zoom Full - Fit image to window",
    "🔍 原始分辨率 (1:1)": "🔍 Native Resolution (1:1)",
    "↩️ 恢复上次视图 (Zoom to Last)": "↩️ Zoom to Last",

    "未加载数据集": "Dataset not loaded",
    "切换到训练执行监视大屏": "Switch to Training Live Monitor",
    "等待样本": "Waiting for samples",
    "预估显存: -- GB": "Est. VRAM: -- GB",
    "⚠ 数据: 未加载": "⚠ Data: Not Loaded",
    "✅ 数据: ": "✅ Data: ",
    "实时增强预览 (Live Augmentation Preview)": "Live Augmentation Preview",
    "数据集: 未就绪": "Dataset: Not Ready",
    "✅ 显存预估: ~": "✅ Est. VRAM: ~",
    "暂无样本": "No Samples",
    "预留：训练曲线图表展示区\\n(Reserved for Dynamic Loss Chart Integration)": "Reserved for Dynamic Loss Chart Integration",
    "⚠ 参数: 待配置": "⚠ Params: Pending",
    "参数: 待配置": "Params: Pending",
    "❌ 环境: 未就绪": "❌ Env: Not Ready",
    "待选择": "Pending",
    "训练执行监控 (Live Training Center)": "Live Training Center",
    "任务配置蓝图 (Task Configuration Dashboard)": "Task Configuration Dashboard",
    "⚠ 显存预估: ~": "⚠ Est. VRAM: ~",
    "环境: 未检测": "Env: Not Detected",
    "无图片": "No Image",
    "已就绪": "Ready",
    " 样本": " Samples",
    "配置健康度 (Configuration Health Score)": "Configuration Health Score",
    "切回任务配置面板": "Switch back to Task Config",
    "实时预测演进 (Live Prediction Evolution)": "Live Prediction Evolution",
    "✅ 参数: 已配置": "✅ Params: Configured",
    "未启用": "Disabled",
    "已加载": "Loaded",
    "样本 ": "Sample ",
    "无预览": "No Preview",
    "❌ 显存: ~": "❌ VRAM: ~",
    "%v 分": "%v Pts",
    "✅ 环境: ": "✅ Env: ",

    "选择 ": "Select ",
    "叠加透明度:": "Overlay Alpha:",
    "重置为默认": "Reset to Default",
    "类别颜色配置": "Class Color Configuration",
    "透明度": "Alpha",
    "点击选择 ": "Click to select ",
    "推理完成后会在这里列出可调整的类别颜色。": "Adjustable class colors will be listed here after inference.",
    "应用到预览": "Apply to Preview",
    "点击修改 ": "Click to edit ",

    "⚡ 已在本地发现匹配权重，可手动勾选使用": "⚡ Matched weights found locally, check to use",
    "暂无 ": "No ",
    "使用预训练权重 (Use Pretrained)": "Use Pretrained Weights",
    "PyTorch 权重 (*.pth);;所有文件 (*)": "PyTorch Weights (*.pth);;All Files (*)",
    "权重文件已存在：\\n": "Weight file already exists:\\n",
    "已取消下载": "Download cancelled",
    "下载失败": "Download failed",
    "预训练模型:": "Pretrained Model:",
    "选择权重文件": "Select Weight File",
    "浏览...": "Browse...",
    "⬇ 下载": "⬇ Download",
    "选择 .pth 权重文件...": "Select .pth weight file...",
    " 的自动下载链接。\\n请前往 OpenMMLab 官方仓库手动下载后放入 pretrain/ 目录。": "'s auto-download link.\\nPlease manually download from OpenMMLab official repo and place in pretrain/.",
    "自有业务权重 (Custom)": "Custom Weights",
    "使用自有权重 (Custom .pth)": "Use Custom Weights (.pth)",
    "公共预训练 (Public)": "Public Pretrained",
    "下载权重": "Download Weights",
    "权重下载失败：\\n": "Weight download failed:\\n",

    # Adding a few more to be safe
    "错误": "Error",
    "警告": "Warning",
    "信息": "Info",
    "确认": "Confirm",
    "取消": "Cancel",
}

for filename in os.listdir(directory):
    if filename.endswith('.py'):
        file_path = os.path.join(directory, filename)
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()

        changed = False
        for k, v in replacements.items():
            if k in content:
                content = content.replace(k, v)
                changed = True

        if changed:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Updated {filename}")

print("Replacement Phase 2.3-2.7 complete.")
