import os

directory = 'd:/WorkSpace/RSegGUI/ui'

replacements = {
    # analysis_panel.py
    "✅ 像素统计已完成 (Analysis Completed)": "✅ Analysis Completed",
    "👆 [AnalysisPanel] 用户手动触发分析": "👆 [AnalysisPanel] User manually triggered analysis",
    "⏸️ [AnalysisPanel] 大数据集 (": "⏸️ [AnalysisPanel] Large dataset (",
    "准备中...": "Preparing...",
    "数据集较大（": "Large dataset (",
    "✕ 取消分析": "✕ Cancel Analysis",
    "✅ [AnalysisPanel] 缓存有效，直接加载结果": "✅ [AnalysisPanel] Cache valid, loading results",
    " 样本)，自动开始分析": " samples), auto starting analysis",
    "🔄 [AnalysisPanel] 小数据集 (": "🔄 [AnalysisPanel] Small dataset (",
    " 个样本），为节省资源请手动开启分析": " samples). To save resources, please start analysis manually.",
    " 样本)，等待用户手动触发": " samples), waiting for manual trigger",
    "📊 启动深度像素统计 (Start Deep Analysis)": "📊 Start Deep Analysis",
    "请先加载数据集": "Please load dataset first",
    "✅ [AnalysisPanel] 分析完成": "✅ [AnalysisPanel] Analysis completed",
    "正在分析: ": "Analyzing: ",
    "❌ [AnalysisPanel] 分析错误: ": "❌ [AnalysisPanel] Analysis error: ",

    # inference_panel.py
    "❌ 模型加载失败: ": "❌ Model load failed: ",
    "✅ 预览PNG已自动保存: ": "✅ Preview PNG auto-saved: ",
    "🚀 开始批量推理: ": "🚀 Start batch inference: ",
    "未选择图像": "No image selected",
    "推理已取消\\n\\n可以重新配置参数后再次运行推理。": "Inference cancelled\\n\\nYou can reconfigure and run again.",
    "选择导出目录": "Select Export Directory",
    "启用多尺度翻转增强 (Enable TTA)": "Enable TTA",
    "导出格式:": "Export Format:",
    "选择要推理的图像": "Select image to infer",
    "重新渲染小图...": "Re-rendering thumbnail...",
    "推理完成": "Inference Complete",
    "\\n\\n结果已保存为GeoTIFF格式。": "\\n\\nResult saved as GeoTIFF.",
    "未知错误": "Unknown error",
    "窗口大小 (Crop Size):": "Crop Size:",
    "模型加载过程中发生错误。\\n\\n错误信息:\\n": "Error occurred during model load.\\n\\nError msg:\\n",
    "ℹ️ 扫描路径下未发现 work_dirs/ 子目录: ": "ℹ️ No work_dirs/ found at: ",
    "正在应用新的可视化设置...": "Applying new visualization settings...",
    "🛑 正在取消推理...": "🛑 Cancelling inference...",
    "未测试": "Not Tested",
    "📤 导出结果（多格式）": "📤 Export Results",
    "导出推理结果": "Export Inference Results",
    "官方可视化预测图输出目录 已保存到 ": "Official visualization output saved to ",
    "配置文件:": "Config File:",
    "选择 MMSegmentation 配置文件": "Select MMSegmentation Config",
    "浏览选择输出路径（自动保存预览PNG）": "Browse output path (auto-save preview PNG)",
    "推理完成后自动保存预览PNG的路径（默认为输入图像所在目录）": "Path to auto-save preview PNG after inference (default: input image directory)",
    "无法读取配置文件。\\n\\n错误信息: ": "Cannot read config file.\\n\\nError msg: ",
    " 个文件": " files",
    "✅ GeoTIFF 已导出: ": "✅ GeoTIFF exported: ",
    "验证配置文件格式": "Validate config format",
    "建议为窗口大小的50%-75%": "Recommended: 50%-75% of crop size",
    "⚠️  模型未加载，无法执行推理": "⚠️  Model not loaded, cannot infer",
    "⚙️  正在运行 ": "⚙️  Running ",
    "请选择历史训练模型...": "Please select trained model...",
    "策略模式:": "Strategy:",
    "请选择有效的批量推理图像目录。": "Please select valid batch inference image directory.",
    "  • 集成MMSegmentation后将生成真实结果\\n": "  • Real results will be generated after MMSegmentation integration\\n",
    "推理返回结果为空": "Inference result is empty",
    "全图缩放": "Full Image Scale",
    "运行单图推理": "Run Single Inference",
    "⏳ 预留图层位置: ": "⏳ Reserved layer position: ",
    "数据集未加载": "Dataset not loaded",
    "   策略模式: ": "   Strategy: ",
    "   检测到 ": "   Detected ",
    "已请求取消测试，正在终止测试进程...": "Cancellation requested, terminating...",
    " | 标注: ": " | Label: ",
    "  • 总像素: ": "  • Total pixels: ",
    "导出NumPy数组格式，便于后续处理": "Export NumPy array format for further processing",
    "导出过程中发生错误。\\n\\n错误信息:\\n": "Error occurred during export.\\n\\nError msg:\\n",
    "✅ TIFF 已导出（无地理信息）: ": "✅ TIFF exported (no geo info): ",
    "浏览选择输入影像": "Browse input image",
    "✅ [推理配置] 已加载配置文件: ": "✅ [Inference] Loaded config: ",
    "大图分块 (GDAL)": "Large Image Tile (GDAL)",
    "已取消": "Cancelled",
    "请先加载推理模型。": "Please load inference model first.",
    "⚠️  配置解析失败: ": "⚠️  Config parse failed: ",
    "【推荐】": "[Recommended]",
    "❌ 取消": "❌ Cancel",
    "🔄 开始执行后台推理...": "🔄 Starting background inference...",
    "✅ 推理完成！\\n\\n": "✅ Inference Complete!\\n\\n",
    "⚠️  类别图例显示警告: ": "⚠️  Class legend warning: ",
    "📐 尺寸: ": "📐 Size: ",
    "   📝 模型名称: ": "   📝 Model Name: ",
    "测试日志、临时运行状态与评估记录目录 已保存到 ": "Test logs and evaluation records saved to ",
    "   推理策略: ": "   Strategy: ",
    "选择模型权重文件": "Select Model Weight File",
    "🛑 推理已取消": "🛑 Inference Cancelled",
    "  • 为节省内存，未生成完整预测掩码\\n": "  • To save memory, full mask not generated\\n",
    "   尺寸: ": "   Size: ",
    "暂无推理结果\\n\\n请加载模型并运行推理，结果将显示在此处。": "No inference results\\n\\nPlease load model and run inference.",
    "没有可用的推理结果。\\n\\n请先运行推理，然后再调整可视化设置。": "No inference results available.\\n\\nPlease run inference before adjusting visualization settings.",
    "🎮 [推理配置] CUDA 可用，默认设备: Auto": "🎮 [Inference] CUDA available, default device: Auto",
    "找不到大图推理结果文件": "Cannot find large image tile result file",
    "请先选择 MMSegmentation 配置文件。": "Please select MMSegmentation config first.",
    "测试数据:": "Test Data:",
    "发现匹配的权重文件": "Found matched weight file",
    "\\n样本: ": "\\nSample: ",
    "📥 已从 GIS 图层同步输入路径: ": "📥 Synced input path from GIS layer: ",
    "⚠️  用户取消推理": "⚠️  User cancelled inference",
    "请先运行推理，然后再导出结果。": "Please run inference first before exporting.",
    "   预览已保存至：": "   Preview saved to:",
    "标注: ": "Label: ",
    "没有可导出的数据。\\n\\n注意：大图分块模式不生成完整掩码，无法导出 PNG/NumPy 格式。": "No data to export.\\n\\nNote: Tile mode doesn't generate full mask, cannot export PNG/NumPy.",
    "   输出文件: ": "   Output File: ",
    "推理可视化面板": "Inference Visualization Panel",
    "：图像 2000–20000 像素范围，标准推理\\n• 大图分块 ": ": image 2000-20000 pixels, standard inference\\n• Tile (GDAL) ",
    "模型测试验证 (Model Test / Evaluation)": "Model Test / Evaluation",
    "批量推理功能待实现...\\n\\n请在实际项目中集成 MMSegmentation 推理 API。": "Batch inference to be implemented...\\n\\nPlease integrate MMSegmentation API in actual project.",
    "模型测试失败: ": "Model test failed: ",
    "透明度已调整: ": "Alpha adjusted: ",
    "CUDA 不可用": "CUDA Not Available",
    ")。\\n\\n当前选择的是'全图缩放'模式，可能导致内存不足。\\n建议切换到'大图分块 (GDAL)'模式。\\n\\n是否继续使用全图缩放模式？": ").\\n\\nCurrently using 'Full Image Scale', which may cause OOM.\\nRecommend switching to 'Large Image Tile (GDAL)'.\\n\\nContinue with Full Image Scale?",
    "已训练模型库:": "Trained Model Repo:",
    "所选文件可能不是有效的 MMSegmentation 配置文件。\\n\\n有效的配置文件应包含 'model' 定义。": "Selected file may not be valid MMSeg config.\\n\\nValid config should contain 'model' definition.",
    "   步长: ": "   Stride: ",
    "无法创建导出目录。\\n\\n错误信息:\\n": "Cannot create export directory.\\n\\nError msg:\\n",
    "推理结果掩码不完整": "Inference mask incomplete",
    "样本预览失败: ": "Sample preview failed: ",
    "选择自动保存预览PNG的文件夹": "Select folder for auto-saving preview PNG",
    "✅ NumPy 已导出: ": "✅ NumPy exported: ",
    "模型名称:": "Model Name:",
    "⚠️  配置解析警告: ": "⚠️  Config parse warning: ",
    "📁 输出路径: ": "📁 Output Path: ",
    "✅ 从库中自动填充了模型配置: ": "✅ Auto-filled model config from repo: ",
    "浏览...": "Browse...",
    "⚠️  当前没有正在进行的推理任务": "⚠️  No ongoing inference task",
    "计算设备:": "Device:",
    "启用": "Enable",
    "解析失败": "Parse Failed",
    "📷 已加载图像: ": "📷 Loaded Image: ",
    "  • 步长: ": "  • Stride: ",
    "❌ 图像读取失败: ": "❌ Image read failed: ",
    "渲染可视化失败: ": "Visualization render failed: ",
    "请先在'输入影像'中选择要推理的图像，\\n或从 GIS 图层中同步图像。": "Please select image in 'Input Image'\\nor sync from GIS layer.",
    "：图像 > 20000 像素超大影像（需 GDAL）": ": image > 20000 pixels (requires GDAL)",
    "创建目录失败": "Create Directory Failed",
    "M像素)。\\n\\n⚠️ 重要提示：\\n'滑窗推理'模式需要在内存中创建完整的结果掩码，\\n对于如此大的图像会导致内存溢出！\\n\\n系统将跳过实际推理以保护内存。\\n\\n✅ 强烈建议：\\n请切换到'大图分块 (GDAL)'模式进行真正的推理！\\n\\n是否继续（将不会进行实际推理）？": "M pixels).\\n\\n⚠️ Note:\\n'Sliding Window' requires full mask in memory,\\nwhich will cause OOM for such large images!\\n\\nSystem will skip actual inference.\\n\\n✅ Recommend:\\nSwitch to 'Large Image Tile (GDAL)'!\\n\\nContinue (no actual inference)?",
    "禁用": "Disable",
    "类别": "Class",
    "   文件大小: ": "   File Size: ",
    " 个\\n": " items\\n",
    "模型加载区 (Model Configuration)": "Model Configuration",
    "🚀 开始单图推理...": "🚀 Start single inference...",
    "⚠️  未设置输出路径，预览PNG将保存到默认路径: ": "⚠️  Output path not set, preview PNG will be saved to: ",
    "样本预览:": "Sample Preview:",
    "取消中...": "Cancelling...",
    "未加载配置": "Config Not Loaded",
    "💡 已根据图像尺寸（": "💡 Auto-selected strategy based on image size (",
    "缺少权重文件": "Missing Weight File",
    "⚠️  请先选择配置文件": "⚠️  Please select config file first",
    "🛑 已发送取消请求...": "🛑 Cancellation request sent...",
    "）自动推荐推理策略": ")",
    "模型加载失败": "Model Load Failed",
    "配置文件不存在:\\n": "Config file does not exist:\\n",
    "请求取消推理": "Request cancel inference",
    "取消测试": "Cancel Test",
    "暂无样本": "No Samples",
    "📷 图像: ": "📷 Image: ",
    "详细错误:\\n": "Detailed error:\\n",
    "文件不存在": "File Not Found",
    "浏览并选择MMSeg配置文件": "Browse and select MMSeg config",
    "大图渲染完成": "Large image rendering complete",
    " 个类别": " classes",
    "  • 批大小: ": "  • Batch Size: ",
    "配置文件格式错误": "Config Format Error",
    "无法读取图像文件。\\n\\n错误信息:\\n": "Cannot read image file.\\n\\nError msg:\\n",
    "选择图像文件或从 GIS 图层同步": "Select image file or sync from GIS layer",
    "测试中": "Testing",
    "来源": "Source",
    "导出GeoTIFF格式，保留地理坐标信息（语义分割标准格式）": "Export GeoTIFF, retain geo info (standard format)",
    "ℹ️ 未关联「数据洞察」数据集，回退到项目根目录扫描：": "ℹ️ Dataset not linked, fallback to project root scan: ",
    "配置文件不存在": "Config File Not Found",
    "   超大图像模式：未生成完整掩码（正常）": "   Large Image Mode: full mask not generated (normal)",
    "未选择导出格式": "Export Format Not Selected",
    "执行与导出 (Action & Export)": "Action & Export",
    "推理完成，但结果处理出现问题:\\n": "Inference complete, but result processing failed:\\n",
    "检测到超大尺寸图像 (": "Detected large image (",
    "类别图例:": "Class Legend:",
    "❌ 推理失败\\n\\n错误信息:\\n": "❌ Inference failed\\n\\nError msg:\\n",
    "🔄 正在加载模型...": "🔄 Loading model...",
    "' 匹配的权重文件：\\n\\n": "' matching weight files:\\n\\n",
    "❌ [推理配置] 配置文件解析失败: ": "❌ [Inference] Config parse failed: ",
    "划分: ": "Split: ",
    "📊 推理结果状态: ": "📊 Inference Result Status: ",
    "无法应用": "Cannot Apply",
    "输入影像:": "Input Image:",
    "进度:": "Progress:",
    "应用失败": "Apply Failed",
    "🎯 策略: ": "🎯 Strategy: ",
    "• 全图缩放 ": "• Full Image Scale ",
    "💡 提示：推理完成后会自动保存预览PNG。\\n   如需其他格式或正式存档，请使用下方的导出功能。": "💡 Tip: Preview PNG is auto-saved after inference.\\n   For other formats or archiving, use Export below.",
    "\\n分块数: ": "\\nTiles: ",
    "⚠️  原始图像为空，无法渲染": "⚠️  Original image empty, cannot render",
    "\\n\\n导出文件:\\n": "\\n\\nExported files:\\n",
    "测试完成": "Test Complete",
    "\\n类别分布:\\n": "\\nClass Distribution:\\n",
    "文件读取错误": "File Read Error",
    "输出路径 (预览PNG):": "Output Path (Preview PNG):",
    "✅ 大图分块推理完成": "✅ Large Image Tile Inference Complete",
    "单图推理": "Single Inference",
    "⚠️  请先选择权重文件": "⚠️  Please select weight file first",
    "✅ [推理配置] 预览PNG输出路径已设置: ": "✅ [Inference] Preview PNG output path set: ",
    "，策略：": ", Strategy: ",
    "选择正式导出目录（可选，默认使用输出路径）": "Select export directory (optional, default: output path)",
    "   重叠率: ": "   Overlap Rate: ",
    "选择批量推理图像目录": "Select Batch Inference Image Directory",
    "权重文件不存在": "Weight File Not Found",
    "置信度阈值:": "Confidence Threshold:",
    "测试状态:": "Test Status:",
    "导出目录 (正式存档):": "Export Directory:",
    "   图像路径: ": "   Image Path: ",
    "浏览导出目录": "Browse Export Directory",
    "\\n标注: ": "\\nLabel: ",
    "置信度阈值，仅对支持置信度输出的模型有效": "Confidence threshold, only valid for models supporting confidence output",
    "成功": "Success",
    "无标签": "No Label",
    "窗口参数:\\n": "Window Params:\\n",
    "输入目录无效": "Invalid Input Directory",
    "有标签": "Has Label",
    "⚠️  检测到超大尺寸图像，建议使用大图分块推理": "⚠️  Detected large image, recommend Tile (GDAL) mode",
    "⚠️  预测掩码为空，无法渲染": "⚠️  Predict mask empty, cannot render",
    "⚠️  未设置输出路径，使用默认路径: ": "⚠️  Output path not set, using default: ",
    "⚠️  用户取消推理，建议切换到大图分块模式": "⚠️  User cancelled, recommend Tile mode",
    "未知的推理策略: ": "Unknown inference strategy: ",
    "  • 输出文件: ": "  • Output File: ",
    "指标": "Metrics",
    "大图分块推理已成功完成！\\n\\n图像: ": "Tile inference completed successfully!\\n\\nImage: ",
    "权重文件:": "Weight File:",
    "应用可视化设置失败: ": "Apply visualization settings failed: ",
    "推理失败": "Inference Failed",
    "请先加载模型。": "Please load model first.",
    "预测结果未找到": "Prediction result not found",
    "   批大小: ": "   Batch Size: ",
    "\\n大图分块推理结果:\\n": "\\nTile Inference Result:\\n",
    "⚠️  配置文件中未找到 CLASSES 或 PALETTE 信息": "⚠️  CLASSES or PALETTE not found in config",
    "🚀 使用真实模型推理（MMSegmentation）\\n\\n": "🚀 Inference with Real Model (MMSegmentation)\\n\\n",
    "批量推理 (Batch Inference)": "Batch Inference",
    "权重文件不存在:\\n": "Weight file not found:\\n",
    "❌ 图像文件不存在: ": "❌ Image file not found: ",
    "选择 MMSeg 配置文件 (.py)": "Select MMSeg Config (.py)",
    "🔧 初始化推理引擎...": "🔧 Initializing inference engine...",
    "\\n💡 超大图像处理模式:\\n": "\\n💡 Large Image Mode:\\n",
    "运行推理 (Run Inference)": "Run Inference",
    "请先选择模型权重文件。": "Please select model weight file first.",
    "推理过程中发生错误。\\n\\n错误信息:\\n": "Error occurred during inference.\\n\\nError msg:\\n",
    "⚠️  预览PNG自动保存失败: ": "⚠️  Preview PNG auto-save failed: ",
    "❌ 配置文件不存在: ": "❌ Config file not found: ",
    "\\n检测到的类别: ": "\\nDetected classes: ",
    "取消中": "Cancelling",
    " 失败: ": " Failed: ",
    "模型未加载": "Model Not Loaded",
    "\\n\\n是否使用此权重文件？": "\\n\\nUse this weight file?",
    "✅ 推理已成功取消": "✅ Inference successfully cancelled",
    "未知模型": "Unknown Model",
    "模型测试开始": "Model Test Started",
    "：图像 ≤ 2000×2000 像素，快速预览\\n• 滑窗推理 ": ": image <= 2000x2000 pixels, fast preview\\n• Sliding Window ",
    "❌ 导出失败: ": "❌ Export failed: ",
    "导出PNG格式的分类结果（无地理信息）": "Export PNG format (no geo info)",
    "✅ 推理完成：": "✅ Inference Complete: ",
    "📊 已加载 ": "📊 Loaded ",
    "💡 [推理配置] 自动选择权重文件: ": "💡 [Inference] Auto-selected weight: ",
    "✅ PNG 已导出: ": "✅ PNG exported: ",
    "测试模型": "Test Model",
    "⚠️  结果处理警告: ": "⚠️  Result process warning: ",
    "请至少选择一种导出格式（GeoTIFF、PNG 或 NumPy）。": "Please select at least one export format (GeoTIFF, PNG, or NumPy).",
    "需要先在 Tab1 加载数据集才能扫描 work_dirs 中的训练记录": "Need to load dataset in Tab1 to scan work_dirs",
    "无推理结果": "No Inference Results",
    "⚠️  无法取消：Worker 不存在": "⚠️  Cannot cancel: Worker not found",
    "批大小 (Batch Size):": "Batch Size:",
    "⚠️  读取原始图像失败: ": "⚠️  Read original image failed: ",
    "模型测试已取消": "Model Test Cancelled",
    "加载模型": "Load Model",
    "  • 窗口总数: ": "  • Total Windows: ",
    "推理模式:": "Inference Mode:",
    "推理已取消": "Inference Cancelled",
    "无法读取原始图像": "Cannot read original image",
    "（未找到训练记录，请先在「数据洞察」标签页加载数据集，或手动指定下方配置文件）": "(No training records found, please load dataset in 'Data Profile' or specify config below)",
    "  • 推理流程已验证成功\\n": "  • Inference process verified successfully\\n",
    "请选择历史训练模型或者手动指定下方文件...": "Select history trained model or specify file below...",
    "  • 分块临时目录: ": "  • Tile Temp Dir: ",
    "⚠️  类别图例显示失败: ": "⚠️  Class legend display failed: ",
    "导出目录未设置": "Export Directory Not Set",
    "🔄 刷新": "🔄 Refresh",
    "⚠️  [推理配置] CUDA 不可用，默认设备: CPU": "⚠️  [Inference] CUDA not available, default: CPU",
    "\\n推理配置:\\n": "\\nInference Config:\\n",
    "请先在数据洞察中加载数据集。": "Please load dataset in Data Profile first.",
    " 推理...": " Inference...",
    "🔄 已刷新已训练模型库": "🔄 Refreshed trained model repo",
    "重新渲染大图...": "Re-rendering large image...",
    "  • 置信度阈值: ": "  • Confidence Threshold: ",
    "重叠率 (Overlap Rate):": "Overlap Rate:",
    "选择模型权重文件 (.pth)": "Select Model Weight (.pth)",
    "测试进度:": "Test Progress:",
    "浏览并选择模型权重文件": "Browse and select model weight file",
    "缺少配置文件": "Missing Config File",
    "M 像素)": "M pixels)",
    "推理结果已成功导出！\\n\\n导出目录:\\n": "Inference results exported successfully!\\n\\nExport Dir:\\n",
    "⚠️  未找到类别信息，将使用默认设置": "⚠️  Class info not found, using default",
    "模型测试完成": "Model Test Complete",
    "运行批量推理": "Run Batch Inference",
    "原始预测结果输出目录 已保存到 ": "Raw prediction output saved to ",
    "❌ 权重文件不存在: ": "❌ Weight file not found: ",
    "推理结果 (Inference Result)": "Inference Result",
    "⚠️  创建类别标签 ": "⚠️  Create class label ",
    "❌ 推理失败: ": "❌ Inference failed: ",
    "图像文件不存在:\\n": "Image file not found:\\n",
    "正在使用训练环境 Python 启动推理子进程...": "Starting inference subprocess using training env...",
    "小图渲染完成": "Small image rendering complete",
    "步长 (Stride):": "Stride:",
    "  • TTA增强: ": "  • TTA: ",
    "未加载": "Not Loaded",
    "应用可视化设置时发生错误。\\n\\n错误信息:\\n": "Error applying visualization settings.\\n\\nError msg:\\n",
    "⚠️ 同步路径无效或不存在: ": "⚠️ Sync path invalid or not found: ",
    "   📦 文件大小: ": "   📦 File Size: ",
    "⚠️  注意：当前使用模拟推理（未集成MMSegmentation）\\n\\n": "⚠️  Note: Currently using mock inference (MMSegmentation not integrated)\\n\\n",
    "超大图像警告": "Large Image Warning",
    "模型测试完成\\n划分: ": "Model Test Complete\\nSplit: ",
    "• 大图分块：图像 > 20000 像素超大影像（需 GDAL，推荐）\\n• 滑窗推理：图像 2000–20000 像素范围，标准推理\\n• 全图缩放：图像 ≤ 2000×2000 像素，快速预览": "• Tile (GDAL): > 20000 px large image (Recommended)\\n• Sliding Window: 2000-20000 px, standard\\n• Full Image Scale: <= 2000x2000 px, fast preview",
    "📁 创建导出目录: ": "📁 Create export dir: ",
    " | 样本: ": " | Sample: ",
    "📤 开始导出结果到: ": "📤 Start exporting results to: ",
    "大图分块推理需要指定输出路径": "Tile inference requires output path",
    "✅ 导出完成，共 ": "✅ Export complete, total ",
    "测试失败": "Test Failed",
    "  • 分块数量: ": "  • Tiles: ",
    "请先选择导出目录。": "Please select export directory first.",
    "⚠️  没有可导出的推理结果": "⚠️  No inference results to export",
    "加载失败": "Load Failed",
    "   TTA增强: ": "   TTA: ",
    "根据GPU显存调整": "Adjust based on GPU VRAM",
    "批量推理": "Batch Inference",
    "滑窗推理": "Sliding Window",
    "图像读取失败": "Image Read Failed",
    "推理策略区 (Inference Strategy)": "Inference Strategy",
    "❌ 后台推理异常: ": "❌ Background inference error: ",
    "模型已就绪": "Model Ready",
    "   窗口大小: ": "   Window Size: ",
    "将推理结果导出为选定的格式（PNG/NumPy/JSON）": "Export inference results to selected formats (PNG/NumPy/JSON)",
    "找到与模型 '": "Found with model '",
    "\\n输出: ": "\\nOutput: ",
    "✅ [推理配置] 已选择权重文件: ": "✅ [Inference] Selected weight file: ",
    "  • 窗口大小: ": "  • Window Size: ",
    "✅ 推理完成": "✅ Inference Complete",
    "⚠️  扫描模型库失败: ": "⚠️  Scan model repo failed: ",
    "⚠️  未选择图像文件": "⚠️  No image file selected",
    "推理完成后会自动保存一个PNG格式的预览图到此路径": "A preview PNG will be auto-saved to this path after inference",
    "✅ 模型已就绪 (Model Ready)": "✅ Model Ready",

    "模型加载": "Model Load",
    "预测": "Predict",
    "导出": "Export",
    "设置": "Settings"
}

files_to_check = ['analysis_panel.py', 'inference_panel.py']
for filename in files_to_check:
    file_path = os.path.join(directory, filename)
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    changed = False
    for k, v in replacements.items():
        if k in content:
            content = content.replace(k, v)
            changed = True

    if changed:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Updated {filename}")

print("Replacement Phase 3 complete.")
